UI5/cli

CONTRIBUTING.md, README.md
Rephrasing, updated labels, updated links
=> [INTERNAL] Update contributing guidelines

README.md
=> [INTERNAL] Update slack badge

.travis.yml, package-lock.json, package.json
Not required for this repository
=> [INTERNAL] Remove lint and test resources

README.md, package.json
To allow usage of fs.copyFile() API
=> [INTERNAL] Update min Node.js version to >=8.5

README.md
Related to https://github.com/SAP/ui5-cli/issues/21
=> [INTERNAL] README: Add links to project configuration details

README.md
ui5-tooling branch got merged into master
=> [INTERNAL] Update openui5-sample-app links

README.md
=> UA Review README.md

README.md, jsdoc.json
Plus some additional page options
=> [INTERNAL] JSDoc: API is private by default

rfcs/0002-project-shims.md
A feature to define configuration and dependency information of a UI5 project outside of that project
=> [RFC] 0002 Project Shims

examples/browsersync/README.md, examples/browsersync/package.json, examples/browsersync/ui5.yaml, examples/browsersync/webapp/index.html
=> [EXAMPLE] Browsersync

README.md
=> [INTERNAL] Fix link to API docs

docs/pages/Workflows.md
=> [INTERNAL] docu: Fix link in docu to FAQ

docs/pages/Configuration.md
=> [INTERNAL] Add bundling section to Configuration.md

docs/pages/Configuration.md
This got implemented with https://github.com/SAP/ui5-cli/pull/245
=> [INTERNAL] Document new UI5 Server settings configuration

CONTRIBUTING.md, README.md, docs/indexJsdoc.md
Badge in readme has already been updated with
e2b8479c56d0aa5376f68fcc5544b7aef352a5ad
Resolves https://github.com/SAP/ui5-tooling/issues/188
=> [INTERNAL] Update Slack invite links

docs/pages/extensibility/CustomTasks.md
As implemented in https://github.com/SAP/ui5-builder/pull/349
=> [INTERNAL] Document new custom task parameter

docs/pages/CLI.md
As implemented in SAP/ui5-cli#265
=> [INTERNAL] Document new 'serve --simple-index' CLI parameter

.github/workflows/deploy-docs.yml
Also update mkdocs-material tag
=> [INTERNAL] GitHub Actions: Remove deprecated actions/npm

docs/pages/Builder.md
Resolves https://github.com/SAP/ui5-builder/issues/374
=> [INTERNAL] Documentation: Fix links

docs/index.md, docs/pages/Builder.md, docs/pages/CLI.md, docs/pages/Configuration.md, docs/pages/GettingStarted.md, docs/pages/SAPUI5.md, docs/updates/migrate-v1.md, docs/updates/migrate-v2.md, mkdocs.yml
=> [INTERNAL] Document new SAPUI5 Consumption

docs/pages/Configuration.md
=> Document Configuration Validation

docs/pages/CLI.md
Depends on https://github.com/SAP/ui5-cli/pull/327
=> [INTERNAL] Add "ui5 remove" cli command documentation

docs/pages/Configuration.md, docs/pages/Project.md, docs/pages/SAPUI5.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/pages/extensibility/ProjectShims.md
depends on https://github.com/SAP/ui5-project/pull/308
=> [INTERNAL] Add "customConfiguration" configuration documentation

CONTRIBUTING.md, README.md, docs/indexJsdoc.md
Follow up of https://github.com/SAP/ui5-tooling/pull/233
=> Update Slack links

docs/pages/extensibility/ProjectShims.md
=> Remove comma from shim documentation

docs/pages/CLI.md, docs/pages/Server.md
Add documentation for CSP Reporting
=> [FEATURE] csp: Add server documentation

docs/pages/Configuration.md
Based on feedback from https://github.com/SAP/ui5-tooling/pull/237
=> [INTERNAL] Configuration Documentation: Update JSDoc section

.github/workflows/reuse-compliance.yml
To align with the other UI5 Tooling repositories
=> [INTERNAL] Workflows: Rename REUSE workflow

README.md, docs/index.md, docs/pages/Builder.md, docs/pages/Configuration.md, docs/pages/FAQ.md, docs/pages/GettingStarted.md, docs/pages/OpenUI5.md, docs/pages/Overview.md, docs/pages/Project.md, docs/pages/SAPUI5.md, docs/pages/Server.md, docs/pages/Troubleshooting.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/stylesheets/extra.css, mkdocs.yml, scripts/resources/CLI.template.md
* mkdocs: Stop loading external fonts
* Document standard tasks and middleware
* Update Getting Started and Development documentation
* Explicitly document OpenUI5 development
* General cleanups and formatting work
=> [INTERNAL] Rework Documentation

docs/pages/Configuration.md
As per https://github.com/SAP/ui5-builder/pull/580
=> [INTERNAL] Configuration.md: Update defaultFileTypes

docs/pages/Configuration.md
See https://github.com/SAP/ui5-tooling/issues/494#issuecomment-916852379
=> [INTERNAL] Configuration.md: Clarify availability of include dependencies config

.github/workflows/deploy-docs.yml, mkdocs.yml, scripts/buildDocs.sh, scripts/serveDocs.sh
Also enable automatic expansion of all navigation items
=> [INTERNAL] Upgrade mkdocs-material to v7.2.6

rfcs/0000-template.md
=> [INTERNAL] RFC Template: Fix comments

docs/pages/extensibility/CustomTasks.md
Resolves https://github.com/SAP/ui5-tooling/issues/580
=> [INTERNAL] CustomTask: Enhance implementation documentation

.github/workflows/github-ci.yml, .github/workflows/reuse-compliance.yml
(cherry picked from commit 4dbdd3522600f0dde8a3cdba83e0629197e8b0a9)
=> [INTERNAL] Enable CI for branches next, main

docs/pages/Configuration.md
Based on input from https://github.com/SAP/ui5-builder/pull/734
=> [INTERNAL] Configuration.md: Update bundleOptions description

mkdocs.yml
See: https://github.com/squidfunk/mkdocs-material/issues/3330
=> [INTERNAL] Fix markdown tabs

docs/updates/migrate-v3.md
JIRA: CPOUI5FOUNDATION-529
Rework task migration guide and enhance it with generateManifestBundle removal.
=> [INTERNAL] Document removal of manifestBundler and generateManifestBundle

docs/stylesheets/extra.css
Based on current stylesheets within OpenUI5.
=> [INTERNAL] docs: Update font-face declarations

docs/updates/migrate-v3.md
Follow-up of https://github.com/SAP/ui5-tooling/pull/688
=> [INTERNAL] Migrate to v3: Minor updates

docs/updates/migrate-v3.md
=> [INTERNAL] Migrate to v3: Breaking changes of jsdoc processor

.github/workflows/security-audit.yml, audit-ci.jsonc
JIRA: CPOUI5FOUNDATION-572
Schedule a security audit on non-default branches.
=> [INTERNAL] Security audit for non-default branches

audit-ci.jsonc
Bugfix: Adds the configuration file for the security audit within the current branch.
More info: https://github.com/SAP/ui5-tooling/pull/706
JIRA: CPOUI5FOUNDATION-572
Currently, the GH Actions workflow is set up in the main branch, but we have decided that the configuration would be held within the scanned branch. This change just adds this configuration
=> [INTERNAL] Add security audit config

docs/pages/Configuration.md, docs/updates/migrate-v3.md
- [INTERNAL] Configuration.md: Remove term 'please' from info note
- [INTERNAL] migrate-v3.md: Update removal of connectUiProxy
=> [INTERNAL] Adjust documentation with UA review comments

.github/workflows/deploy-docs.yml, package.json, scripts/buildSchema.js
JIRA: CPOUI5FOUNDATION-584
Generate ui5-workspace.yaml schema that complies with the [local dependency resolution spec](https://github.com/SAP/ui5-tooling/blob/rfc-local-dependency-resolution/rfcs/0006-local-dependency-resolution.md#workspace-configuration-file)
For further details, check the [RFC 0006 Local Dependency Resolution](https://github.com/SAP/ui5-tooling/blob/rfc-local-dependency-resolution/rfcs/0006-local-dependency-resolution.md)
This change depends on https://github.com/SAP/ui5-project/pull/543
=> [INTERNAL] ui5-workspace.yaml schema generation

docs/pages/Benchmarking.md, docs/pages/Configuration.md, docs/pages/FileSystem.md, docs/pages/Workspace.md, docs/updates/migrate-v3.md, mkdocs.yml
* Add Workspace and File System documentation
* Update Configuration and migration guide with new name restrictions + minor changes
* Minor updates in benchmarking guide
=> [INTERNAL] Add Workspace, FileSystem documentation page

package-lock.json, package.json
The project accidentially published a breaking change as a minor release
Let's pin this dev-dependency until that is sorted out
=> [INTERNAL] package.json: Pin json-schema-ref-parser to v10.0.1

docs/pages/Builder.md, docs/updates/migrate-v3.md
As per code changes via https://github.com/SAP/ui5-project/pull/542
=> [INTERNAL] Adopt details about generateThemeDesignerResources activation

scripts/resources/CLI.template.md
According to new requirements for v3
=> [INTERNAL] Update CLI.template.md

docs/pages/Builder.md, docs/updates/migrate-v3.md
Follow-up of https://github.com/SAP/ui5-tooling/pull/769
=> [INTERNAL] Docs: Apply suggestions

docs/pages/Workspace.md
Fixes: https://github.com/SAP/ui5-tooling/issues/794
=> [INTERNAL] docs: Fix link to 'Local Dependency Resolution' RFC

docs/updates/migrate-v3.md
The order and content of the migration information should be improved, e.g. for the ESM transformation whn using tooling modules directly.
=> [INTERNAL] Improve migration information, e.g. for ESM.

rfcs/0013-configuration.md
[**View rendered version**](https://github.com/SAP/ui5-tooling/blob/rfc-configuration/rfcs/0013-configuration.md)
=> [RFC] 0013 Configuration

docs/pages/FAQ.md, docs/pages/SAPUI5.md, docs/pages/Troubleshooting.md
- Remove usage of yarn
- Remove v2 specific documentation parts
=> [INTERNAL] Adjust documentation regarding package managers

audit-ci.jsonc
Updates https://github.com/SAP/ui5-tooling/pull/844 pattern, so it would cover all the cases.
=> [INTERNAL] Adjust semver pattern for v2 audit

docs/pages/ESSupport.md
List the reserved variable names inside Template Literal expressions.
=> [INTERNAL] ESSupport.md: Add a section about reserved variable names

docs/pages/extensibility/CustomServerMiddleware.md
JIRA: CPOUI5FOUNDATION-491
Related: https://github.com/SAP/karma-ui5/issues/410
=> [INTERNAL] CustomServerMiddleware: Document karma-ui5 integration caveats

docs/pages/Troubleshooting.md
=> [INTERNAL] Document UI5_LOG_LVL in Troubleshooting page

docs/pages/Troubleshooting.md
See: https://github.com/SAP/ui5-project/pull/642
JIRA: CPOUI5FOUNDATION-715
=> [INTERNAL] Update Data Directory documentation

docs/index.md, docs/updates/migrate-v1.md, docs/updates/migrate-v2.md, examples/browsersync/ui5.yaml
Adjust documentation according to https://github.com/SAP/ui5-cli/pull/660
=> [INTERNAL] ui5.yaml: Use double quotes for string values

.github/workflows/github-ci.yml
=> [INTERNAL] update gh actions dependencies

README.md
Some docs updates, e.g. fixing link to RFC 0006.
=> [INTERNAL] Address some docs issues

CONTRIBUTING.md
=> [INTERNAL] CONTRIBUTING.md: Add section about multi branch development

docs/index.md, docs/pages/Configuration.md, docs/pages/OpenUI5.md, docs/pages/SAPUI5.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/pages/extensibility/ProjectShims.md
JIRA: CPOUI5FOUNDATION-835
https://github.com/SAP/ui5-tooling/issues/701
=> [FEATURE] Reflect specVersion: 4.0 into documentation

docs/pages/Configuration.md, docs/updates/migrate-v4.md
- Add @ui5/builder as peer dependency to @ui5/project in migration guide
- Adjust Configuration.md
=> [INTERNAL] Enhance documentation

docs/pages/ESSupport.md
Add note about ES2023 support with https://github.com/SAP/ui5-cli/releases/tag/v3.11.0.
JIRA: CPOUI5FOUNDATION-852
=> [INTERNAL] docs/pages/ESSupport.md: Reflect es2023 support

docs/pages/Builder.md, docs/pages/Server.md
Add documentation for new task enhanceManifest and processor manifestEnhancer
JIRA: CPOUI5FOUNDATION-831
=> [FEATURE] Add documentation for new task enhanceManifest and processor manifestEnhancer

jsdoc.json, package-lock.json, package.json
See https://github.com/SAP/ui5-builder/pull/1072
=> [INTERNAL] jsdoc: Apply excludes for @ui5/builder v4

.github/workflows/deploy-docs.yml
Those files should only be updated via main branch deployment.
=> [INTERNAL] Remove schema / 404 page update from v3 deployment

docs/pages/Project.md
Fixes https://github.com/SAP/ui5-tooling/issues/994
=> [INTERNAL] Project.md: Use default instead of non existing main branch

docs/pages/Project.md
Cherry-pick of https://github.com/SAP/ui5-tooling/pull/995
=> [INTERNAL] v3: Project.md: Use default instead of non existing main branch

package-lock.json
Fixes https://github.com/SAP/ui5-tooling/security/dependabot/23 in UI5 Tooling V3
=> [INTERNAL] Update package-lock.json

package-lock.json, package.json
=> refactor: Give a name to the monorepo
