README.md
Workspace support got added with version 1.0 as per https://yarnpkg.com/lang/en/docs/workspaces/ (first paragraph)
CC: @pavelkornev
=> [INTERNAL] Readme: Clarify minimum yarn version

.travis.yml
As this module does not execute any tests, the use of multiple node
versions is unnecessary. Also, this prevents duplicative JSDoc builds.
=> [INTERNAL] Travis: Use node lts

jsdoc.json
Wrapping navigation names is necessary because our module names are very
long.
=> [INTERNAL] JSDoc: Set wrap option and add openGraph meta data

rfcs/0004-simple-build-extensibility.md
Add a feature for basic customization of how a single UI5 project is being built.
Follow up of https://github.com/SAP/ui5-tooling/pull/4
=> [RFC] 0004 Simple Build Extensibility

rfcs/0005-server-middleware-extensibility.md
Read the current draft here: **[0005-server-middleware-extensibility.md](https://github.com/SAP/ui5-tooling/blob/rfc-server-middleware-extensibility/rfcs/0005-server-middleware-extensibility.md)**
=> [RFC] 0005 Server Middleware Extensibility

rfcs/0006-properties-file-encoding.md, rfcs/0007-properties-file-encoding.md
Add a fix for properties file encoding when they are part of a build or served such that they can always be interpreted as UTF-8 encoded files.
Read: [0007-properties-file-encoding.md](https://github.com/SAP/ui5-tooling/blob/rfc-properties-file-encoding/rfcs/0007-properties-file-encoding.md)
=> [RFC] 0007 Properties File Encoding

docs/pages/Configuration.md
- Cachebuster docu is moved to correct location
- *.properties file encoding option is documented
=> [INTERNAL] Adapt project configuration documentation

jsdoc.json
See https://github.com/SAP/ui5-builder/pull/304
=> [INTERNAL] JSDoc: Exclude @ui5/builder JSTokenizer

docs/pages/Configuration.md
For current rendering (missing newlines) see: https://sap.github.io/ui5-tooling/pages/Configuration/#properties_1
=> [INTERNAL] Add missing newline for correct mkdocs rendering

.github/workflows/deploy-docs.yml
Likely caused by switch from npm action to direct command execution
=> [INTERNAL] GitHub Actions: Fix permissions denied error on jsdoc build

docs/pages/ConsumingSAPUI5Libraries.md
This page is linked in every SAPUI5 library's README.md.
It is a placeholder for the guide about how to consume
SAPUI5 libraries in the future.
=> [INTERNAL] add consuming SAPUI5 libraries page

docs/pages/Builder.md, docs/pages/Configuration.md, docs/pages/Project.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/pages/extensibility/ProjectShims.md
The new type 'theme-library' requires this spec version 1.1.
See https://github.com/SAP/ui5-project/pull/252 and
https://github.com/SAP/ui5-builder/pull/285
=> [INTERNAL] Add specification version 1.1

docs/pages/CLI.md, docs/pages/GettingStarted.md, package.json
BREAKING CHANGE:
Support for older Node.js releases has been dropped.
Only Node.js v10 or higher is supported.
=> [BREAKING] Require Node.js >= 10

docs/index.md, docs/pages/Builder.md, docs/pages/CLI.md, docs/pages/Configuration.md, docs/pages/GettingStarted.md, docs/pages/Project.md, docs/pages/SAPUI5.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/pages/extensibility/ProjectShims.md, docs/updates/migrate-v1.md, docs/updates/migrate-v2.md, mkdocs.yml, package.json
This PR or at least the branch should be used to collect all UI5 Tooling 2.0 documentation changes and enhancements.
We should also think about whether we copy all current documentation into a "1.x Documentation" sub-section for archival.
=> UI5 Tooling 2.0

README.md
Use the same invite app as on https://openui5.org/community/ that is hosted on the SAP Mentors Account for SAP Cloud Platform Cloud Foundry. Also a direct link to the #tooling channel in Slack.
=> [FIX] Replace Slack invite link, direct link to Slack

docs/pages/extensibility/CustomTasks.md
This PR fixes the links of the custom builder task page pointing to the UI5 Tooling documentation.
=> docs: fix the links for custom builder task section

docs/pages/Configuration.md
Was never true. JSDoc got fixed in
https://github.com/SAP/ui5-builder/pull/474
=> [INTERNAL] Configuration.md: Fix decorateBootstrapModuled default

README.md
Currently, UI5 Tooling has no open platform for public questions and answers.  
Hence, I'm proposing Stack Overflow Q&A which has a growing number of UI5 Tooling questions.  
This PR also helps improving discoverability of those questions.
=> [INTERNAL] README: add link to "ui5-tooling" questions

docs/pages/Builder.md
Adds new task generateThemeDesignerResources (since @ui5/cli v2.8.0)
=> [INTERNAL] Docs - Builder: Update Standard Tasks

docs/pages/OpenUI5.md, docs/pages/SAPUI5.md
Although being added by their respective commands (like `ui5 use openui5@latest`, the examples were missing the version within their ui5.yaml files. Really small adjustment, hope the commit message is according to the guidelines.
=> [INTERNAL] Add missing version to ui5.yaml example

docs/pages/Troubleshooting.md
PRs where this process was already used:
* https://github.com/SAP/ui5-builder/pull/488
* https://github.com/SAP/ui5-builder/pull/390
JIRA: CPOUI5FOUNDATION-261
=> [INTERNAL] Document the UI5 Tooling benchmarking process

.github/workflows/issues.yml
Currently only applies to issues labeled "information required"
=> [INTERNAL] GitHub Action: Flag and close stale issues

.github/workflows/deploy-docs.yml, docs/stylesheets/extra.css, scripts/buildDocs.sh, scripts/serveDocs.sh
Starting with v6.1.0 and still with the latest v7.3.0, our custom CSS
classes are not applied in tables. Instead, they are rendered as strings.
Examples from CLI and Builder pages:
This partially reverts https://github.com/SAP/ui5-tooling/pull/556
=> [INTERNAL] Revert mkdocs-material to v6.0.2

docs/pages/Builder.md
Add build task 'replaceBuildtime' to the table of standard
tasks in the Builder documentation.
JIRA: CPOUI5FOUNDATION-327
=> [INTERNAL] Add build task 'replaceBuildtime' to Builder docs

docs/pages/Builder.md, docs/updates/migrate-v3.md
* Update minify task order based on https://github.com/SAP/ui5-builder/pull/724
* Fix generateComponentPreload order for libraries. It has always been
executed before generateLibraryPreload.
=> [INTERNAL] Update/fix task order

.github/in-solidarity.yml
The https://github.com/ietf/terminology project offers a huge collection of non inclusive terminologies.
=> [INTERNAL] Enhance existing in-solidarity check by using the ietf/terminology configuration

.github/workflows/deploy-docs.yml, docs/updates/migrate-v3.md, mkdocs.yml, scripts/buildDocs.sh, scripts/serveDocs.sh
* Fix some errors in the docs
* Add the v3 migration guide to the navigation (basically making it "public")
* Upgrad mkdocs-material image for M1 support
=> [INTERNAL] Update v3 Migration Documentation

package-lock.json, package.json, scripts/buildSchema.js
The recursive option is available since Node v10.12, which makes the
use of thirdparty packages obsolete for most use cases.
=> [INTERNAL] Use native fs.mkdir instead of mkdirp

.github/workflows/deploy-docs.yml, scripts/Dockerfile, scripts/buildDocs.sh, scripts/buildImage.sh, scripts/hash.js, scripts/serveDocs.sh
JIRA: CPOUI5FOUNDATION-565
Relates to: https://github.com/SAP/ui5-tooling/pull/697
This change creates a new documentation release workflow that enables versioning.
It extends the MkDocs squidfunk/mkdocs-material image by adding [mike](https://github.com/jimporter/mike) to it.
The GitHub Actions workflow is also being extended to support the new feature.
URLs of the documentation would be changed with a version number prepending the path. In order to "keep" old links available for the end users, there's a custom redirect for GH Pages.
=> [INTERNAL] v2 docs versioning

.github/workflows/deploy-docs.yml
Docs versioning workflow needs to be adjusted. 
The `buildDocs.sh` file runs the `npm run jsdoc-generate` which creates a new folder (`site`) within the CI/CD environment.
This folder needs to have the correct access rights.
=> [INTERNAL] Fix for v2 docs versioning workflow

.github/workflows/deploy-docs.yml
Docs versioning workflow needs to be adjusted.
The buildDocs.sh file runs the npm run jsdoc-generate which creates a new folder (site) within the CI/CD environment.
This folder needs to have the correct access rights.
For `v2`: https://github.com/SAP/ui5-tooling/pull/714
=> [INTERNAL] Fix for docs versioning workflow

.github/workflows/deploy-docs.yml
Adds additional, not `mike`/`mkdocs` related documents with a separate commit message instead of squashing the previous one. That way the git history is kept.
=> [INTERNAL] Bugfix: Keep gh-pages history for mike

docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md
Related changes:
* https://github.com/SAP/ui5-project/pull/514
* https://github.com/SAP/ui5-server/pull/547
* https://github.com/SAP/ui5-project/pull/520
=> [INTERNAL] CustomTask/Middleware: Update documentation with v3 enhancements

README.md, docs/index.md, docs/pages/Builder.md, docs/pages/Configuration.md, docs/pages/Overview.md, docs/pages/Project.md, docs/pages/Server.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/pages/fsInterface.md, docs/updates/migrate-v2.md, rfcs/0008-resource-tagging-during-build.md, rfcs/0010-ui5-builder-bundling-refactoring.md
Now all the API links need to point explicitly to the /v2/api path. This way links from the documentation would always be correct
=> [INTERNAL] Switch API links to explicitly point to /v2/api documentation

docs/updates/migrate-v3.md
UI5 Tooling modules currently require at least Node v16.18.0
=> [INTERNAL] Migrate v3: Align minimum Node version

docs/pages/Configuration.md, docs/pages/Server.md, docs/updates/migrate-v3.md
> This removes the "/proxy" endpoint and the corresponding
"connectUi5Proxy" middleware from the standard ui5-server.
Internally, this middleware made use of the connect-openui5 proxy
implementation (https://github.com/SAP/connect-openui5#proxy).
> More sophisticated proxy solutions for ui5-server are already available
in the form of custom middleware extensions from the UI5-community.
> The UI5 Team might provide a dedicated custom middleware extension,
with similar functionality, in the future.
Relates to: https://github.com/SAP/ui5-server/pull/550
JIRA: CPOUI5FOUNDATION-598
=> [INTERNAL] Removes connectUi5Proxy documentation

docs/index.md, docs/pages/Configuration.md, docs/pages/TasksAndProcessors.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/updates/migrate-v3.md, examples/browsersync/README.md
Update the code samples to use additionally ESM import and export statements. The respective code blocks are displayed in tabs "CommonJS" and "ESM".
=> [INTERNAL] Update usages of CJS require/exports to ESM import/export

scripts/resources/custom404.html
This is an issue with the Docs. With the implementation of versioned documentation, we wanted to support also the legacy links. That's why, when a resource is not found we check whether this resource is in the versioned documentation and if not, we redirect to the same path of the stable release. If the resource is already versioned, but is not found, we just redirect to the stable release's root path.
=> [INTERNAL] Fix infinite looping for unknown sources

docs/pages/OpenUI5.md, lib/jsdoc/plugin/template/layout.tmpl, overrides/partials/footer.html, scripts/resources/CLI.template.md
This PR replaces the term "master" in links pointing to the default branch. 
**Advantages:**
- The link is stable also when default branch is switched without the branch renaming feature of github
- "master" is identified as non inclusive language
=> [INTERNAL] Use default branch identifier '-' instead of hardcoded branch name for external links

audit-ci.jsonc
Taffdb is only used during jsdoc build and contains only data for jsdoc generation. After jsdoc build db is destroyed.
=> [INTERNAL] audit-ci(v2): Add security alert for taffdb 'GHSA-mxhp-79qh-mcx6' to allow list

audit-ci.jsonc
The exception for the `taffdb` needs to be defined within the scanned branch config
=> [FIX] V2 security audit add exception

versions.json
Redirect "stable" links to UI5 Tooling V3 documentation.
**Before this PR**:
https://sap.github.io/ui5-tooling/stable/ --> https://sap.github.io/ui5-tooling/v2/
https://sap.github.io/ui5-tooling/next/ --> https://sap.github.io/ui5-tooling/v3/
**After merging this PR**:
https://sap.github.io/ui5-tooling/stable/ --> https://sap.github.io/ui5-tooling/v3/
https://sap.github.io/ui5-tooling/next/ --> https://sap.github.io/ui5-tooling/v3/
=> [INTERNAL] docu: Switch stable alias to v3 documentation

.github/workflows/deploy-docs.yml, overrides/main.html
- Add a note informing user about UI5 Tooling is in maintenance
- Remove stable alias from mkdocs run
=> [INTERNAL] v2: Put UI5 Tooling V2 in maintenance

docs/updates/migrate-v3.md
V3 is officially released. Therefore removing warning note about V3.
=> [INTERNAL] migrate-v3.md: Remove warning note

docs/pages/extensibility/CustomTasks.md
It needs to be a named export. Currently it would overwrite the default
export (=main task function).
=> [INTERNAL] CustomTask: Fix CommonJS example for 'determineRequiredDependencies' export

docs/pages/extensibility/CustomTasks.md
Order of parameters should be identical in ESM and CommonJS examples
=> [INTERNAL] CustomTask: Fix order in JSDoc for 'determineRequiredDependencies' callback

docs/pages/Server.md
See: https://github.com/SAP/ui5-server/pull/580
=> [INTERNAL] csp: Update documentation for sap-csp-policies target level increase

docs/pages/Builder.md
See: https://github.com/SAP/ui5-project/pull/583
=> [INTERNAL] Builder.md: Mark task generateVersionInfo as enabled for jsdoc build

CONTRIBUTING.md, README.md, SUPPORT.md, docs/indexJsdoc.md
Link is limited by Slack to 400 people but never expires.
=> [INTERNAL] Fix Slack invitation link

docs/pages/Troubleshooting.md
=> [INTERNAL] Introduce UI5_DATA_DIR env

docs/pages/Configuration.md
This configuration will enabled by https://github.com/SAP/ui5-project/pull/639
=> [INTERNAL] Configuration: Builder excludes for type module

audit-ci.jsonc
People should be motivated to migrate to v3. 
We shall still have some awareness regarding the vulnerabilities that might appear in v2 with a higher severity.
=> [INTERNAL] v2: Change security audit reporting level to high or critical only

mkdocs.yml
URI needs to be manually defined in case the branch is not "master".
=> [INTERNAL] Fix edit button on documentation pages

overrides/main.html
The link described in the main mike/mkdocs-material docs is not quite correct and in some cases leads to bad landings: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=base+url#version-warning
For example, trying to follow the deprecation link on this page: https://sap.github.io/ui5-tooling/v2/pages/extensibility/CustomServerMiddleware/
The issue is because the `base_url` produces a backtrack, but not a real base URL. However, it takes into account the versioning!
Now, it's been adjusted to lead always to the root page of v3
**Note:** This is a docs adjustment for v2 branch!
=> [INTERNAL] v2: stabilize deprecation anouncement link

docs/pages/Configuration.md, docs/pages/extensibility/CustomTasks.md, docs/updates/migrate-v3.md
JIRA: CPOUI5FOUNDATION-724
This PR aims to improve the documentation by providing correct information based on a related change for custom tasks subscription & execution order behaviour: https://github.com/SAP/ui5-project/pull/628
=> [INTERNAL] Improve documentation after code refactoring

docs/updates/migrate-v3.md
Addresses the outstanding comments from this PR: https://github.com/SAP/ui5-tooling/pull/874
https://github.com/SAP/ui5-tooling/pull/874#discussion_r1345367144
=> [INTERNAL] Improve `uglify` migration docs

docs/pages/Configuration.md
fixes: https://github.com/SAP/ui5-tooling/issues/879
=> [FIX] Correct links to API ref for ModuleBundleDefinition

docs/pages/Builder.md, docs/pages/Project.md
This change does not introduce any changes, but just moves the (project) Types section from [`/Builder`](https://sap.github.io/ui5-tooling/stable/pages/Builder/#types) page to the [`/Project`](https://sap.github.io/ui5-tooling/stable/pages/Project/) page where it actually belongs.
=> [INTERNAL] Reorder documentation

docs/index.md, docs/pages/Configuration.md, docs/pages/OpenUI5.md, docs/pages/SAPUI5.md, docs/pages/extensibility/CustomServerMiddleware.md, docs/pages/extensibility/CustomTasks.md, docs/pages/extensibility/ProjectShims.md
Adds information about specVersion 3.2
**_Note:_** This change shouldn't be merged before:
- https://github.com/SAP/ui5-builder/pull/951
- https://github.com/SAP/ui5-project/pull/673
=> [INTERNAL] specVersion 3.2 docs

.github/workflows/deploy-docs.yml, .github/workflows/github-ci.yml, package-lock.json, package.json, scripts/buildSchema.js, scripts/isWorkspace.js
BREAKING CHANGE:
Support for older Node.js and npm releases has been dropped.
Only Node.js 20.11.x and >=21.2.0 as well as npm v10 or higher are supported.
JIRA: CPOUI5FOUNDATION-800
=> [BREAKING] Require Node.js 20.11.x/>=21.2.0 and npm >=10

docs/pages/Builder.md, docs/updates/migrate-v3.md, docs/updates/migrate-v4.md
This task was enabled since at least v2 (probably since v0 already):
https://github.com/SAP/ui5-builder/blob/v2.11.11/lib/types/application/ApplicationBuilder.js#L46
Not sure why we missed it in this list. Also fix formatting in the
markdown
=> [INTERNAL] Builder: generateFlexChangesBundle task is always enabled for applications

package-lock.json, package.json
In one of the former releaes, the json-schema-ref-parser did not export correctly the default export.
So we had to configure a fixed version before the bug was introduced.
This is fixed with https://github.com/APIDevTools/json-schema-ref-parser/releases/tag/v11.2.3, so we can use the latest version again.
=> [INTERNAL] Update @apidevtools/json-schema-ref-parser to latest version

docs/pages/Configuration.md
Up until UI5 Tooling v3, the bundle option "usePredefineCalls" defaults to "false" and has to be activated explicitly in a custom bundle configuration.
For default bundles, such as Component-preload or self-contained bundle (sap-ui-custom.js), there is no way to use the option apart from re-defining the whole bundle via custom bundle definition.
With UI5 Tooling v4 bundles are generated with the usage sap.ui.predefine calls instead of the former default function wrapper. This leads to smaller bundle sizes and less overhead at runtime.
As the option only affects the internal handling of bundling without affecting the actual users,
the option is removed completely, instead of just changing the default value of the option.
Implementation covered in …
=> [FEATURE] Bundling: Remove option 'usePredefineCalls'

docs/updates/migrate-v4.md
JIRA: CPOUI5FOUNDATION-847
Some of the required documentation would be handled with: https://github.com/SAP/ui5-tooling/pull/963
This migration guide tries to reflects changes described here: https://github.com/SAP/ui5-tooling/issues/701
=> [INTERNAL] UI5 Tooling v4 migration guide

docs/updates/migrate-v4.md
Related: https://github.com/SAP/ui5-tooling/issues/988
=> [INTERNAL] Migrate v4: Add troubleshooting chapter regarding incompatible manifest versions

scripts/resources/CLI.template.md
The docs had not been updated with the correct node version requirements after the v4 release.
=> [FIX] Updated node version requirements in docs

README.md
UI5 Tooling Version 4 is released for some weeks, so consumers should migrate to Version 4 instead of Version 3
=> [INTERNAL] README.md: Adjust migration note to highlight Version 4

docs/pages/GettingStarted.md, docs/updates/migrate-v4.md, scripts/resources/CLI.template.md
Related: https://github.com/SAP/ui5-tooling/issues/1017
=> [INTERNAL] Clarify supported Node.js versions

.github/workflows/security-audit.yml, audit-ci.jsonc
Also checking the main branch to be notified about vulnerabilities based
on the released packages.
Although the main branch is covered by GitHub security checks and
dependabot updates, it could be missed that some vulnerabilities have
been solved already but not released yet.
Also removing the unnecessary "npm install". Audit CI checks based on
the existing lockfile.
=> [INTERNAL] Audit CI: Enable check on main branch
